[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dmadb-docs"
authors = [{name = "Tom", email = "t.n.lawson@bham.ac.uk"}]
dynamic = ["version", "description"]
